// umpires-master.js
// PIEZA - diccionario de umpires 2026, indexado por NOMBRE NORMALIZADO (sin acentos, minusculas).
// Generado desde el CSV de umpires (77 filas). El feed de MLB da el nombre del umpire de plato,
// que puede no calzar exacto, por eso se normaliza (traducir-umpire.js hace la misma normalizacion).
// Campos REALES del CSV: name (nombre original), zone_factor, zone_type, k_per_game, bb_per_game, k_tier.
// NOTA: este CSV no trae 'favors' ni 'so_g'; se usa lo que existe. zone_factor>1 = zona amplia (favorece pitcher).

var UMPIRES_MASTER_2026 = {
  "john bacon": { name: "John Bacon", zone_factor: 1.395, zone_type: "Wide", k_per_game: 16.4, bb_per_game: 4.0, k_tier: "C_NEUTRAL" },
  "paul clemons": { name: "Paul Clemons", zone_factor: 1.248, zone_type: "Wide", k_per_game: 14.8, bb_per_game: 4.5, k_tier: "E_STRONG_ANTI_K" },
  "chris segal": { name: "Chris Segal", zone_factor: 1.233, zone_type: "Wide", k_per_game: 15.6, bb_per_game: 4.7, k_tier: "D_ANTI_K" },
  "jansen visconti": { name: "Jansen Visconti", zone_factor: 1.209, zone_type: "Wide", k_per_game: 17.0, bb_per_game: 5.2, k_tier: "C_NEUTRAL" },
  "ryan blakney": { name: "Ryan Blakney", zone_factor: 1.201, zone_type: "Wide", k_per_game: 17.3, bb_per_game: 5.3, k_tier: "B_PLUS_K" },
  "dj reyburn": { name: "D.J. Reyburn", zone_factor: 1.192, zone_type: "Wide", k_per_game: 17.6, bb_per_game: 5.4, k_tier: "B_PLUS_K" },
  "cory blaser": { name: "Cory Blaser", zone_factor: 1.184, zone_type: "Wide", k_per_game: 17.2, bb_per_game: 5.4, k_tier: "C_NEUTRAL" },
  "clint vondrak": { name: "Clint Vondrak", zone_factor: 1.184, zone_type: "Wide", k_per_game: 16.2, bb_per_game: 5.2, k_tier: "D_ANTI_K" },
  "ryan wills": { name: "Ryan Wills", zone_factor: 1.154, zone_type: "Wide", k_per_game: 19.5, bb_per_game: 6.3, k_tier: "A_ELITE_K" },
  "brian walsh": { name: "Brian Walsh", zone_factor: 1.137, zone_type: "Wide", k_per_game: 16.7, bb_per_game: 5.7, k_tier: "C_NEUTRAL" },
  "alfonso marquez": { name: "Alfonso Márquez", zone_factor: 1.137, zone_type: "Wide", k_per_game: 16.5, bb_per_game: 5.6, k_tier: "C_NEUTRAL" },
  "john tumpane": { name: "John Tumpane", zone_factor: 1.133, zone_type: "Wide", k_per_game: 16.7, bb_per_game: 5.7, k_tier: "C_NEUTRAL" },
  "bill miller": { name: "Bill Miller", zone_factor: 1.123, zone_type: "Wide", k_per_game: 20.6, bb_per_game: 7.1, k_tier: "A_ELITE_K" },
  "quinn wolcott": { name: "Quinn Wolcott", zone_factor: 1.123, zone_type: "Wide", k_per_game: 20.9, bb_per_game: 7.2, k_tier: "A_ELITE_K" },
  "brian onora": { name: "Brian O'Nora", zone_factor: 1.117, zone_type: "Wide", k_per_game: 19.7, bb_per_game: 6.9, k_tier: "A_ELITE_K" },
  "bruce dreckman": { name: "Bruce Dreckman", zone_factor: 1.113, zone_type: "Wide", k_per_game: 18.6, bb_per_game: 6.5, k_tier: "A_ELITE_K" },
  "alan porter": { name: "Alan Porter", zone_factor: 1.105, zone_type: "Wide", k_per_game: 16.3, bb_per_game: 5.9, k_tier: "C_NEUTRAL" },
  "john libka": { name: "John Libka", zone_factor: 1.103, zone_type: "Wide", k_per_game: 15.7, bb_per_game: 5.7, k_tier: "D_ANTI_K" },
  "carlos torres": { name: "Carlos Torres", zone_factor: 1.095, zone_type: "Slightly wide", k_per_game: 18.0, bb_per_game: 6.5, k_tier: "B_PLUS_K" },
  "mike muchlinski": { name: "Mike Muchlinski", zone_factor: 1.087, zone_type: "Slightly wide", k_per_game: 17.4, bb_per_game: 6.4, k_tier: "B_PLUS_K" },
  "ryan additon": { name: "Ryan Additon", zone_factor: 1.08, zone_type: "Slightly wide", k_per_game: 21.3, bb_per_game: 8.1, k_tier: "A_ELITE_K" },
  "dan merzel": { name: "Dan Merzel", zone_factor: 1.075, zone_type: "Slightly wide", k_per_game: 16.8, bb_per_game: 6.3, k_tier: "C_NEUTRAL" },
  "jordan baker": { name: "Jordan Baker", zone_factor: 1.063, zone_type: "Slightly wide", k_per_game: 15.9, bb_per_game: 6.1, k_tier: "D_ANTI_K" },
  "marvin hudson": { name: "Marvin Hudson", zone_factor: 1.062, zone_type: "Slightly wide", k_per_game: 14.9, bb_per_game: 5.9, k_tier: "E_STRONG_ANTI_K" },
  "hunter wendelstedt": { name: "Hunter Wendelstedt", zone_factor: 1.057, zone_type: "Slightly wide", k_per_game: 16.8, bb_per_game: 6.5, k_tier: "C_NEUTRAL" },
  "scott barry": { name: "Scott Barry", zone_factor: 1.053, zone_type: "Slightly wide", k_per_game: 18.3, bb_per_game: 7.1, k_tier: "B_PLUS_K" },
  "todd tichenor": { name: "Todd Tichenor", zone_factor: 1.046, zone_type: "Slightly wide", k_per_game: 14.4, bb_per_game: 5.9, k_tier: "E_STRONG_ANTI_K" },
  "stu scheurwater": { name: "Stu Scheurwater", zone_factor: 1.045, zone_type: "Slightly wide", k_per_game: 19.2, bb_per_game: 7.7, k_tier: "A_ELITE_K" },
  "mike estabrook": { name: "Mike Estabrook", zone_factor: 1.039, zone_type: "Slightly wide", k_per_game: 16.5, bb_per_game: 6.6, k_tier: "C_NEUTRAL" },
  "rob drake": { name: "Rob Drake", zone_factor: 1.038, zone_type: "Slightly wide", k_per_game: 17.1, bb_per_game: 6.9, k_tier: "C_NEUTRAL" },
  "lance barrett": { name: "Lance Barrett", zone_factor: 1.037, zone_type: "Slightly wide", k_per_game: 16.2, bb_per_game: 6.6, k_tier: "D_ANTI_K" },
  "adam hamari": { name: "Adam Hamari", zone_factor: 1.03, zone_type: "Slightly wide", k_per_game: 14.3, bb_per_game: 6.0, k_tier: "E_STRONG_ANTI_K" },
  "lance barksdale": { name: "Lance Barksdale", zone_factor: 1.02, zone_type: "Average", k_per_game: 18.1, bb_per_game: 7.6, k_tier: "B_PLUS_K" },
  "adrian johnson": { name: "Adrian Johnson", zone_factor: 1.017, zone_type: "Average", k_per_game: 20.3, bb_per_game: 8.8, k_tier: "A_ELITE_K" },
  "david rackley": { name: "David Rackley", zone_factor: 1.01, zone_type: "Average", k_per_game: 16.9, bb_per_game: 7.1, k_tier: "C_NEUTRAL" },
  "nate tomlinson": { name: "Nate Tomlinson", zone_factor: 1.01, zone_type: "Average", k_per_game: 16.9, bb_per_game: 7.1, k_tier: "C_NEUTRAL" },
  "roberto ortiz": { name: "Roberto Ortiz", zone_factor: 1.009, zone_type: "Average", k_per_game: 17.1, bb_per_game: 7.3, k_tier: "C_NEUTRAL" },
  "jeremie rehak": { name: "Jeremie Rehak", zone_factor: 1.005, zone_type: "Average", k_per_game: 16.8, bb_per_game: 7.2, k_tier: "C_NEUTRAL" },
  "nick mahrley": { name: "Nick Mahrley", zone_factor: 1.005, zone_type: "Average", k_per_game: 16.8, bb_per_game: 7.2, k_tier: "C_NEUTRAL" },
  "nestor ceja": { name: "Nestor Ceja", zone_factor: 1.001, zone_type: "Average", k_per_game: 14.5, bb_per_game: 6.4, k_tier: "E_STRONG_ANTI_K" },
  "james hoye": { name: "James Hoye", zone_factor: 0.998, zone_type: "Average", k_per_game: 16.4, bb_per_game: 7.1, k_tier: "C_NEUTRAL" },
  "dan iassogna": { name: "Dan Iassogna", zone_factor: 0.997, zone_type: "Average", k_per_game: 18.0, bb_per_game: 7.9, k_tier: "B_PLUS_K" },
  "mark wegner": { name: "Mark Wegner", zone_factor: 0.995, zone_type: "Average", k_per_game: 18.6, bb_per_game: 8.2, k_tier: "A_ELITE_K" },
  "tripp gibson": { name: "Tripp Gibson", zone_factor: 0.991, zone_type: "Average", k_per_game: 19.1, bb_per_game: 8.6, k_tier: "A_ELITE_K" },
  "erich bacchus": { name: "Erich Bacchus", zone_factor: 0.99, zone_type: "Average", k_per_game: 17.1, bb_per_game: 7.6, k_tier: "C_NEUTRAL" },
  "alex mackay": { name: "Alex MacKay", zone_factor: 0.986, zone_type: "Average", k_per_game: 18.2, bb_per_game: 8.2, k_tier: "B_PLUS_K" },
  "brennan miller": { name: "Brennan Miller", zone_factor: 0.973, zone_type: "Average", k_per_game: 17.1, bb_per_game: 7.9, k_tier: "C_NEUTRAL" },
  "james jean": { name: "James Jean", zone_factor: 0.966, zone_type: "Slightly tight", k_per_game: 13.4, bb_per_game: 6.4, k_tier: "E_STRONG_ANTI_K" },
  "dan bellino": { name: "Dan Bellino", zone_factor: 0.963, zone_type: "Slightly tight", k_per_game: 14.6, bb_per_game: 6.9, k_tier: "E_STRONG_ANTI_K" },
  "shane livensparger": { name: "Shane Livensparger", zone_factor: 0.962, zone_type: "Slightly tight", k_per_game: 15.6, bb_per_game: 7.3, k_tier: "D_ANTI_K" },
  "mark ripperger": { name: "Mark Ripperger", zone_factor: 0.96, zone_type: "Slightly tight", k_per_game: 17.0, bb_per_game: 8.0, k_tier: "C_NEUTRAL" },
  "manny gonzalez": { name: "Manny Gonzalez", zone_factor: 0.96, zone_type: "Slightly tight", k_per_game: 16.7, bb_per_game: 7.9, k_tier: "C_NEUTRAL" },
  "chris conroy": { name: "Chris Conroy", zone_factor: 0.95, zone_type: "Slightly tight", k_per_game: 17.8, bb_per_game: 8.7, k_tier: "B_PLUS_K" },
  "edwin moscoso": { name: "Edwin Moscoso", zone_factor: 0.949, zone_type: "Slightly tight", k_per_game: 17.9, bb_per_game: 8.7, k_tier: "B_PLUS_K" },
  "chad whitson": { name: "Chad Whitson", zone_factor: 0.948, zone_type: "Slightly tight", k_per_game: 15.4, bb_per_game: 7.4, k_tier: "D_ANTI_K" },
  "junior valentine": { name: "Junior Valentine", zone_factor: 0.946, zone_type: "Slightly tight", k_per_game: 16.8, bb_per_game: 8.2, k_tier: "C_NEUTRAL" },
  "alex tosi": { name: "Alex Tosi", zone_factor: 0.945, zone_type: "Slightly tight", k_per_game: 15.0, bb_per_game: 7.3, k_tier: "E_STRONG_ANTI_K" },
  "doug eddings": { name: "Doug Eddings", zone_factor: 0.934, zone_type: "Slightly tight", k_per_game: 15.6, bb_per_game: 7.7, k_tier: "D_ANTI_K" },
  "charlie ramos": { name: "Charlie Ramos", zone_factor: 0.93, zone_type: "Slightly tight", k_per_game: 15.7, bb_per_game: 7.9, k_tier: "D_ANTI_K" },
  "laz diaz": { name: "Laz Diaz", zone_factor: 0.927, zone_type: "Slightly tight", k_per_game: 17.0, bb_per_game: 8.6, k_tier: "C_NEUTRAL" },
  "malachi moore": { name: "Malachi Moore", zone_factor: 0.927, zone_type: "Slightly tight", k_per_game: 15.4, bb_per_game: 7.8, k_tier: "D_ANTI_K" },
  "chris guccione": { name: "Chris Guccione", zone_factor: 0.926, zone_type: "Slightly tight", k_per_game: 15.0, bb_per_game: 7.6, k_tier: "E_STRONG_ANTI_K" },
  "adam beck": { name: "Adam Beck", zone_factor: 0.926, zone_type: "Slightly tight", k_per_game: 15.9, bb_per_game: 8.0, k_tier: "D_ANTI_K" },
  "andy fletcher": { name: "Andy Fletcher", zone_factor: 0.922, zone_type: "Slightly tight", k_per_game: 15.1, bb_per_game: 7.7, k_tier: "D_ANTI_K" },
  "nic lentz": { name: "Nic Lentz", zone_factor: 0.918, zone_type: "Slightly tight", k_per_game: 17.6, bb_per_game: 9.2, k_tier: "B_PLUS_K" },
  "chad fairchild": { name: "Chad Fairchild", zone_factor: 0.914, zone_type: "Slightly tight", k_per_game: 12.1, bb_per_game: 6.6, k_tier: "E_STRONG_ANTI_K" },
  "willie traynor": { name: "Willie Traynor", zone_factor: 0.913, zone_type: "Slightly tight", k_per_game: 17.7, bb_per_game: 9.4, k_tier: "B_PLUS_K" },
  "gabe morales": { name: "Gabe Morales", zone_factor: 0.905, zone_type: "Slightly tight", k_per_game: 15.1, bb_per_game: 8.0, k_tier: "D_ANTI_K" },
  "derek thomas": { name: "Derek Thomas", zone_factor: 0.903, zone_type: "Slightly tight", k_per_game: 18.6, bb_per_game: 10.4, k_tier: "A_ELITE_K" },
  "will little": { name: "Will Little", zone_factor: 0.901, zone_type: "Slightly tight", k_per_game: 16.9, bb_per_game: 9.1, k_tier: "C_NEUTRAL" },
  "ben may": { name: "Ben May", zone_factor: 0.879, zone_type: "Tight", k_per_game: 18.0, bb_per_game: 10.6, k_tier: "B_PLUS_K" },
  "brock ballou": { name: "Brock Ballou", zone_factor: 0.872, zone_type: "Tight", k_per_game: 14.4, bb_per_game: 8.2, k_tier: "E_STRONG_ANTI_K" },
  "sean barber": { name: "Sean Barber", zone_factor: 0.863, zone_type: "Tight", k_per_game: 16.4, bb_per_game: 9.7, k_tier: "C_NEUTRAL" },
  "jim wolf": { name: "Jim Wolf", zone_factor: 0.853, zone_type: "Tight", k_per_game: 13.4, bb_per_game: 8.0, k_tier: "E_STRONG_ANTI_K" },
  "tom hanahan": { name: "Tom Hanahan", zone_factor: 0.849, zone_type: "Tight", k_per_game: 14.3, bb_per_game: 8.6, k_tier: "E_STRONG_ANTI_K" },
  "vic carapazza": { name: "Vic Carapazza", zone_factor: 0.844, zone_type: "Tight", k_per_game: 13.9, bb_per_game: 8.4, k_tier: "E_STRONG_ANTI_K" },
  "austin jones": { name: "Austin Jones", zone_factor: 0.84, zone_type: "Tight", k_per_game: 16.0, bb_per_game: 10.0, k_tier: "D_ANTI_K" }
};
